import { IMAGES } from "./images";

export const quizData = {
  easy: [
    { q: "what is a capybara?", options: ["a type of fish", "the world's largest rodent", "a small bird", "a reptile"], answer: 1 },
    { q: "where do capybaras originally come from?", options: ["Africa", "Australia", "South America", "Asia"], answer: 2 },
    { q: "are capybaras good swimmers?", options: ["no they hate water", "they can swim a little", "yes they are excellent swimmers", "only in shallow water"], answer: 2 },
    { q: "what do capybaras mainly eat?", options: ["fish", "insects", "grasses and plants", "small mammals"], answer: 2 },
    { q: "how much can an adult capybara weigh?", options: ["up to 10 lbs", "up to 50 lbs", "up to 140 lbs", "up to 300 lbs"], answer: 2 },
  ],
  medium: [
    { q: "how long can capybaras hold their breath underwater?", options: ["30 seconds", "up to 5 minutes", "up to 15 minutes", "they can't go underwater"], answer: 1 },
    { q: "what is a group of capybaras called?", options: ["a pack", "a herd", "a flock", "a colony"], answer: 1 },
    { q: "which animal is the capybara most closely related to?", options: ["beavers", "guinea pigs", "rats", "rabbits"], answer: 1 },
    { q: "what sound do capybaras make when they're happy?", options: ["they bark", "they purr and click", "they meow", "they don't make sounds"], answer: 1 },
    { q: "how many toes do capybaras have on their front feet?", options: ["3", "4", "5", "6"], answer: 1 },
    { q: "why do other animals like to sit on capybaras?", options: ["they're warm", "they're calm and non-threatening", "they smell good", "they provide food"], answer: 1 },
  ],
  expert: [
    { q: "what is the scientific name for capybaras?", options: ["Hydrochoerus hydrochaeris", "Capybara maximus", "Rodentia giganticus", "Caviidae supremus"], answer: 0 },
    { q: "what does 'capybara' roughly translate to?", options: ["water dog", "master of the grasses", "big friend", "gentle giant"], answer: 1 },
    { q: "in Japan, what do they float in capybara hot spring baths?", options: ["rubber ducks", "yuzu fruits", "flower petals", "bamboo leaves"], answer: 1 },
    { q: "how many babies can a capybara have in one litter?", options: ["1 to 2", "2 to 8", "8 to 12", "12 to 15"], answer: 1 },
    { q: "which pope reportedly declared capybaras to be fish?", options: ["Pope Francis", "Pope Benedict XVI", "a 16th century pope for Lent purposes", "this never happened"], answer: 2 },
    { q: "what is the average lifespan of a capybara in the wild?", options: ["3 to 5 years", "6 to 12 years", "15 to 20 years", "20 to 25 years"], answer: 1 },
    { q: "capybaras have a special scent gland on their nose called a:", options: ["morillo", "sebaceous pad", "nasal bulb", "olfactory ridge"], answer: 0 },
  ],
};

export const statesData = [
  { name: "Alabama", status: "legal" }, { name: "Alaska", status: "illegal" },
  { name: "Arizona", status: "legal" }, { name: "Arkansas", status: "permit" },
  { name: "California", status: "illegal" }, { name: "Colorado", status: "illegal" },
  { name: "Connecticut", status: "illegal" }, { name: "Delaware", status: "permit" },
  { name: "Florida", status: "permit" }, { name: "Georgia", status: "illegal" },
  { name: "Hawaii", status: "illegal" }, { name: "Idaho", status: "legal" },
  { name: "Illinois", status: "illegal" }, { name: "Indiana", status: "legal" },
  { name: "Iowa", status: "permit" }, { name: "Kansas", status: "legal" },
  { name: "Kentucky", status: "legal" }, { name: "Louisiana", status: "legal" },
  { name: "Maine", status: "permit" }, { name: "Maryland", status: "illegal" },
  { name: "Massachusetts", status: "illegal" }, { name: "Michigan", status: "illegal" },
  { name: "Minnesota", status: "illegal" }, { name: "Mississippi", status: "legal" },
  { name: "Missouri", status: "permit" }, { name: "Montana", status: "legal" },
  { name: "Nebraska", status: "permit" }, { name: "Nevada", status: "permit" },
  { name: "New Hampshire", status: "illegal" }, { name: "New Jersey", status: "illegal" },
  { name: "New Mexico", status: "legal" }, { name: "New York", status: "illegal" },
  { name: "North Carolina", status: "permit" }, { name: "North Dakota", status: "legal" },
  { name: "Ohio", status: "permit" }, { name: "Oklahoma", status: "legal" },
  { name: "Oregon", status: "illegal" }, { name: "Pennsylvania", status: "permit" },
  { name: "Rhode Island", status: "illegal" }, { name: "South Carolina", status: "legal" },
  { name: "South Dakota", status: "legal" }, { name: "Tennessee", status: "permit" },
  { name: "Texas", status: "legal" }, { name: "Utah", status: "illegal" },
  { name: "Vermont", status: "illegal" }, { name: "Virginia", status: "permit" },
  { name: "Washington", status: "illegal" }, { name: "West Virginia", status: "legal" },
  { name: "Wisconsin", status: "illegal" }, { name: "Wyoming", status: "legal" },
];

export const stateGrid = [
  { abbr: "AK", name: "Alaska", row: 0, col: 0 },
  { abbr: "ME", name: "Maine", row: 0, col: 10 },
  { abbr: "WI", name: "Wisconsin", row: 1, col: 5 },
  { abbr: "VT", name: "Vermont", row: 1, col: 9 },
  { abbr: "NH", name: "New Hampshire", row: 1, col: 10 },
  { abbr: "WA", name: "Washington", row: 2, col: 0 },
  { abbr: "MT", name: "Montana", row: 2, col: 1 },
  { abbr: "ND", name: "North Dakota", row: 2, col: 2 },
  { abbr: "MN", name: "Minnesota", row: 2, col: 3 },
  { abbr: "MI", name: "Michigan", row: 2, col: 6 },
  { abbr: "NY", name: "New York", row: 2, col: 8 },
  { abbr: "MA", name: "Massachusetts", row: 2, col: 9 },
  { abbr: "CT", name: "Connecticut", row: 2, col: 10 },
  { abbr: "OR", name: "Oregon", row: 3, col: 0 },
  { abbr: "ID", name: "Idaho", row: 3, col: 1 },
  { abbr: "SD", name: "South Dakota", row: 3, col: 2 },
  { abbr: "IA", name: "Iowa", row: 3, col: 3 },
  { abbr: "IL", name: "Illinois", row: 3, col: 4 },
  { abbr: "IN", name: "Indiana", row: 3, col: 5 },
  { abbr: "OH", name: "Ohio", row: 3, col: 6 },
  { abbr: "PA", name: "Pennsylvania", row: 3, col: 7 },
  { abbr: "NJ", name: "New Jersey", row: 3, col: 8 },
  { abbr: "RI", name: "Rhode Island", row: 3, col: 9 },
  { abbr: "NV", name: "Nevada", row: 4, col: 0 },
  { abbr: "WY", name: "Wyoming", row: 4, col: 1 },
  { abbr: "NE", name: "Nebraska", row: 4, col: 2 },
  { abbr: "MO", name: "Missouri", row: 4, col: 3 },
  { abbr: "KY", name: "Kentucky", row: 4, col: 5 },
  { abbr: "WV", name: "West Virginia", row: 4, col: 6 },
  { abbr: "VA", name: "Virginia", row: 4, col: 7 },
  { abbr: "MD", name: "Maryland", row: 4, col: 8 },
  { abbr: "DE", name: "Delaware", row: 4, col: 9 },
  { abbr: "CA", name: "California", row: 5, col: 0 },
  { abbr: "UT", name: "Utah", row: 5, col: 1 },
  { abbr: "CO", name: "Colorado", row: 5, col: 2 },
  { abbr: "KS", name: "Kansas", row: 5, col: 3 },
  { abbr: "AR", name: "Arkansas", row: 5, col: 4 },
  { abbr: "TN", name: "Tennessee", row: 5, col: 5 },
  { abbr: "NC", name: "North Carolina", row: 5, col: 6 },
  { abbr: "SC", name: "South Carolina", row: 5, col: 7 },
  { abbr: "AZ", name: "Arizona", row: 6, col: 1 },
  { abbr: "NM", name: "New Mexico", row: 6, col: 2 },
  { abbr: "OK", name: "Oklahoma", row: 6, col: 3 },
  { abbr: "LA", name: "Louisiana", row: 6, col: 4 },
  { abbr: "MS", name: "Mississippi", row: 6, col: 5 },
  { abbr: "AL", name: "Alabama", row: 6, col: 6 },
  { abbr: "GA", name: "Georgia", row: 6, col: 7 },
  { abbr: "HI", name: "Hawaii", row: 7, col: 0 },
  { abbr: "TX", name: "Texas", row: 7, col: 3 },
  { abbr: "FL", name: "Florida", row: 7, col: 7 },
];

export const galleryItems = [
  { src: IMAGES.capyBath, alt: "capybara in a bath", category: "water", caption: "spa day vibes" },
  { src: IMAGES.capySwim, alt: "capybara swimming", category: "water", caption: "just keep swimming" },
  { src: IMAGES.capyFriends, alt: "capybara with friends", category: "friends", caption: "squad goals" },
  { src: IMAGES.capyFlower, alt: "capybara with flower crown", category: "cute", caption: "flower crown queen" },
  { src: IMAGES.capyBaby, alt: "baby capybara", category: "cute", caption: "tiny and perfect" },
  { src: IMAGES.capyBaby2, alt: "baby capybara closeup", category: "cute", caption: "look at this face" },
  { src: IMAGES.capyMajestic, alt: "majestic capybara", category: "cute", caption: "absolutely majestic" },
  { src: IMAGES.capyWatermelon, alt: "capybara eating watermelon", category: "cute", caption: "snack time" },
  { src: IMAGES.userCapy1, alt: "nose to nose", category: "mine", caption: "nose to nose" },
  { src: IMAGES.userCapy2, alt: "fan art approved", category: "mine", caption: "fan art approved" },
  { src: IMAGES.userCapy3, alt: "petal bath royalty", category: "mine water", caption: "petal bath royalty" },
  { src: IMAGES.userCapy4, alt: "capybara kiss", category: "mine water", caption: "capybara kiss" },
  { src: IMAGES.userCapy5, alt: "lazy afternoon", category: "mine cute", caption: "lazy afternoon" },
  { src: IMAGES.userCapy6, alt: "capy cafe date", category: "mine friends", caption: "capy cafe date" },
  { src: IMAGES.userCapy7, alt: "couch buddies", category: "mine friends", caption: "couch buddies" },
  { src: IMAGES.userCapy8, alt: "snack time at the zoo", category: "mine friends", caption: "snack time at the zoo" },
  { src: IMAGES.userCapy9, alt: "golden hour vibes", category: "mine cute", caption: "golden hour vibes" },
];

export const newsItems = [
  {
    date: "Feb 2026",
    title: "Japanese Zoo Opens New Capybara Hot Spring for Winter",
    desc: "the Nagasaki Bio Park just unveiled a brand new onsen area for their capybaras, complete with yuzu fruits floating in the water. visitors are losing their minds and honestly same.",
    link: "https://www.youtube.com/watch?v=dGmwIhXnyeo",
  },
  {
    date: "Jan 2026",
    title: "Capybara Cafe in Tokyo Breaks Visitor Record",
    desc: "a cafe in Tokyo where you can hang out with capybaras while drinking coffee just hit 500,000 visitors. the capybaras reportedly remain unbothered by this achievement.",
    link: "https://www.atlasobscura.com/places/capybara-land",
  },
  {
    date: "Dec 2025",
    title: "Capybara Named Animal of the Year by Internet Poll",
    desc: "in a completely unsurprising turn of events, the internet has once again voted capybaras as the best animal. they beat out cats by a narrow margin which honestly feels like an upset.",
    link: "https://en.wikipedia.org/wiki/Capybara",
  },
  {
    date: "Nov 2025",
    title: "New Study: Capybaras Reduce Stress in Other Animals",
    desc: "scientists confirmed what we already knew. being near a capybara literally lowers cortisol levels in other animals. they are walking therapy sessions and I need one immediately.",
    link: "https://wwf.ca/stories/eight-facts-about-capybara/",
  },
];

export const funFacts = [
  { emoji: "🏊", title: "born to swim", text: "capybaras have webbed feet and can hold their breath for up to 5 minutes. they basically live in the water." },
  { emoji: "👑", title: "biggest rodent ever", text: "they can weigh up to 140 pounds. that is a very large rodent and I respect it deeply." },
  { emoji: "🐾", title: "everyone loves them", text: "birds, monkeys, rabbits, even crocodiles just chill with capybaras. they are the universal friend." },
  { emoji: "🌿", title: "grass is life", text: "they eat about 6 to 8 pounds of grass per day. that is their whole thing and they are committed to it." },
  { emoji: "🛁", title: "hot spring royalty", text: "in Japan they put capybaras in hot spring baths with yuzu fruits. this is the most wholesome thing on earth." },
  { emoji: "🦷", title: "teeth never stop", text: "their teeth grow continuously throughout their life. the grass keeps them filed down. nature figured it out." },
  { emoji: "😴", title: "sleep in water", text: "they can fall asleep in the water with just their nose above the surface. that is the life I want." },
  { emoji: "🐣", title: "community parents", text: "baby capybaras are raised by the whole group, not just their parents. it takes a village and capybaras know that." },
];
